django_intro/urls.py
from django.contrib import admin
from django.urls import path,include #include 해야함 ㅎ
from django_app import views   #설정한 django_app 폴더 안에 있는 view.py를 가져오기!


# app.route 설정과 비슷한 원리
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),  #path('url', 메소드)     #플라스크처럼 아래에 함수를 정의하는게 아닌, view.py에 정의한다
    path('whoami/', views.me),
    path('lunch/', views.lunch),
    path('lotto/', views.lotto),
    path('hello/<str:name>/', views.hello), #헬로 뒤에 뭐가들어와도 name변수에 담기게됨
    path('cube/<int:cube_num>/', views.cube),
    #인자 컨버터
    # str:스트링
    #int : 0또는 양의정수
    #slug : 문자 또는 숫자, 하이픈, 밑줄
    path('todos/', include('todo.urls')) #todo라는 앱 안에 urls 내용을 포함시키겠다
    
]

todo/urls.py
from django.urls import path
from . import views #현재폴더(todo)에 있는 views 파일 추가


app_name='todo'

urlpatterns = [
    path('', views.index), #/todos 가 이미 되있음(생략)
    path('new/', views.new),
    path('create/', views.create),
    path('<int:id>/', views.read),
    path('todo_create/', views.todo_create),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

]

django_app/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length= 50) #스트링 타입을 저장하는 필드,최대길이 50으로 줌
    deadline = models.DateField()
    
    
    def __str__(self):
        return self.title #원랜 todo object 였는데 오버라이딩 해줬음

django_app/views.py
from django.shortcuts import render
import random

# Create your views here.
def index(request):
    return render(request, 'index.html')
    
    
def me(request):
    return render(request, 'me.html')
    
def lunch(request):
    menu_list = ['김카', '20층']
    pick = random.choice(menu_list)
    return render(request, 'lunch.html', {'pick':pick})
    
def lotto(request):
    lotto_number = random.sample(range(1,46),6)
    return render(request, 'lotto.html', {'lotto_number':lotto_number})
    
def hello(request,name): #name 인자값 받았음
    return render(request, 'hello.html', {'name':name})

def cube(request, cube_num):
    result = cube_num**3
    return render(request, 'cube.html', {'result':result})

todo/views.py
from django.shortcuts import render, redirect
from todo.models import Todo


# Create your views here.
def index(request):
    todos= Todo.objects.all() #todo object 전부 부르기
    return render(request,'todo/index.html',{'todos':todos})
    
def new(request):
    return render(request, 'todo/new.html')
    
def create(request):
    title = request.POST.get('title')
    deadline = request.POST.get('deadline')
    todo = Todo(title=title, deadline=deadline)
    todo.save() #add와 commit이 합쳐진 로직
    
    return redirect('/todos/')
    
def read(request,id):
    todo = Todo.objects.get(id=id)
    return render(request, 'todo/read.html',{'todo':todo})
    
def todo_create(request):
    if request.method =='POST':
        title = request.Post.get('title')
        deadline = request.Post.get('deadline')
        Todo.objects.create(title = title, deadline=deadline) #만들고 save까지 한번에!!
        return redirect('/todos/')
        
    else:
        return render(request, 'todo/todo_create.html')
        
def delete(request,id):
    todo = Todo.objects.get(id=id)
    todo.delete()
    return redirect('/todos/')
    
def update(request,id):
    todo = Todo.objects.get(id=id)
    if request.method =='POST':
        todo.title = request.Post.get('title')
        todo.deadline = request.POST.get('deadline')
        todo.save()
        return redirect('/todos')
        #저장로직
        
    else:
        deadline = todo.deadline.strftime("%Y-%m-%d")
        return render(request, 'todo/update.html',{'todo':todo, 'deadline':deadline})
        #폼 보여주기 

django_app/templates/cube.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>the result : {{result}}</h1>
</body>
</html>

django_app/templates/hello.html
hello {{name}}

django_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>WE ARE THE CHAMPION MY FRIENDS</h1>
</body>
</html>

django_app/templates/lotto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{lotto_number}}</h1>
</body>
</html>

django_app/templates/lunch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{pick}}</h1>
</body>
</html>

django_app/templates/me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>I AM THE KING!</h1>
    <h2>do you understand?!</h2>
    <h3></h3>
</body>
</html>

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="/todos/new/">글작성</a>
    <a href="/todos/todo_create/">합쳐진로직</a>
    {%block body_block%}
    
    {%endblock%}
</body>
</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}
{% block body_block %}
    {% for todo in todos %}
    
        <h1>{{todo.title}} </h1>
        <h2>{{todo.deadline}}</h2>
        <a href="/todos/{{todo.id}}">글보기</a>
        <a href="/todos/{{todo.id}}/delete">삭제</a>
        <a href='/todos/{{todo.id}}/update'>수정</a>
    {% endfor %}
{% endblock %}

todo/templates/todo/new.html
{%extends 'todo/base.html' %}
{%block body_block%}
<form action='/todos/create/' method='POST'>
    {%csrf_token%}   <!--csrf 보안 만들어서 보내기---> 
      <div class="form-group">
        <label for="title">title</label>
        <input name="title" type="text" class="form-control" id="title" placeholder="제목을 입력해주세요!">
      </div>
      <div class="form-group">
        <label for="deadline">DEAD LINE</label>
        <input name="deadline" type='date' id="deadline" class="form-control" placeholder="yyyy.mm.dd">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
</form>


{%endblock%}

todo/templates/todo/read.html
{% extends 'todo/base.html' %}
{% block body_block%}
    <h1>{{todo.title}}</h1>
    <h2>{{todo.deadline}}</h2>
    <a href="/todos/{{todo.id}}">글보기</a>
    <a href="/todos/{{todo.id}}/delete">삭제</a>
    <a href='/todos/{{todo.id}}/update'>수정</a>
    <a href="/todos/{% url 'todo:update' id=todo.id %}">또다른 수정</a>
{% endblock %}

todo/templates/todo/todo_create.html
{% extends 'todo/base.html' %}

{% block body_block %}
<form action='/todos/create/' method='POST'>
    {%csrf_token%}
    <input type="text" name="title" id='title'/>
    <input type='date' name='deadline' id='deadline'/>
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

todo/templates/todo/update.html
{% extends 'todo/base.html' %}

{% block body_block %}
<form action='/todos/{{todo.id}}/update/' method='POST'>
    {%csrf_token%}
    <input type="text" name="title" id='title' value={{todo.title}} />
    <input type='date' name='deadline' id='deadline' value="{{deadline}}"/>
    <input type="submit" value="Submit"/>
</form>
{% endblock %}